<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_User_Question</name>
   <tag></tag>
   <elementGuidId>12c6782d-43c3-4e7e-91fd-475a0cd57424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;account-question&quot;]/div/fieldset/legend/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;account-question&quot;]/div/fieldset/legend/h1</value>
   </webElementXpaths>
</WebElementEntity>
