<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>endUser_Question</name>
   <tag></tag>
   <elementGuidId>4e2705ab-aee9-48bd-aa0a-32bbabbb7e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main-form-group&quot;]/fieldset/legend/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;main-form-group&quot;]/fieldset/legend/h1</value>
   </webElementXpaths>
</WebElementEntity>
