<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Upload_Pdf</name>
   <tag></tag>
   <elementGuidId>33874bd7-ccf9-4fa7-a3dd-25e6e7a5913e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-include.ng-scope:nth-child(1) ng-view.ng-scope section.formsection.ng-scope div.maincontent div.tab-content div.tab-pane.ng-scope.active:nth-child(2) div.view div.ng-scope div.viewcontent gp-view.ng-isolate-scope div.gpview-row:nth-child(30) ng-include.ng-scope:nth-child(3) div.gpview-template.ng-scope div.gpview-rowmain > h3.ng-binding:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>row.subject | highlight:query</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload_Pdf</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0FF27A09-3D47-43CA-88B8-A594B7C16C46&quot;)/ng-include[@class=&quot;ng-scope&quot;]/div[@class=&quot;gpview-template ng-scope&quot;]/div[@class=&quot;gpview-rowmain&quot;]/h3[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
