<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Environmental_Details</name>
   <tag></tag>
   <elementGuidId>aee4dd39-85fe-4712-b86f-e7382d1a25a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;overview&quot;]/table[1]/tbody/tr[2]/td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;overview&quot;]/table[1]/tbody/tr[2]/td[1]/a</value>
   </webElementXpaths>
</WebElementEntity>
