<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_DifferentPlans</name>
   <tag></tag>
   <elementGuidId>3b46be70-dbdb-49d3-b31b-4b6b0aa10b8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-Different.Plans-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-Different.Plans-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
