<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Help_File_Formats</name>
   <tag></tag>
   <elementGuidId>96a12524-dc9d-4df7-bebb-f1b0abc659fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[6]//div[1]//div[1]//div[1]//div[1]//details[1]//summary[1]//span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
