<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Planning_Application_Details</name>
   <tag></tag>
   <elementGuidId>13fb8558-b290-4fb1-9eaa-6acd77765db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;overview&quot;]/table[1]/tbody/tr[1]/td[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;overview&quot;]/table[1]/tbody/tr[1]/td[1]/a</value>
   </webElementXpaths>
</WebElementEntity>
